### ISSUE TITLE
matchedFilter infinite memory allocation in R versions >3.3

### ISSUE THREAD

**Issue by Pohnert-Lab** [sneumann/xcms#291]
Hello,

I'm encountering a strange problem when I want to do peak picking using the matchedFilter algorithm on my high resolution GC-MS data. Because of the high resolution, I'm using a very small step (0,001). In older R versions (3.3), this works fine. In newer versions however, the resulting Rscript.exe starts to allocate memory until it reaches 100% RAM usage and my system freezes (I have 16GB RAM). This occurs even with only 1 file to process.

centWave and matchedFilter with low resolution parameters still work fine though.

Unfortunately I cannot just continue using older R versions because I want to combine the XCMS package with other packages that require newer versions. Also, centWave doesn't work that well with my GC data, it creates a lot more false positives than matchedFilter.

Do you have any suggestions on what to do?

Thank you for your time.

**Comment by sneumann** [comment]
We've had memory issues a while back, but they were fixed in the meantime. 
Which versions are you running ? Could you try to upgrade if they are not the newest ? 
Yours, Steffen

**Comment by Pohnert-Lab** [comment]
Thanks for the hint! In R version 3.5, I indeed have the newest version of xcms (3.2.0). I reinstalled it to double check, but I still have the same problem.

In the old R version however (3.3.3), the installed xcms version is 1.50.1!

I then tried to install the old xcms(1.50.1) into R v3.5, but it wouldn't work because of "different R internals".
Same with installing the new xcms(3.2.0) into the old R v3.3.3, wouldn't work because of incompatible package dependencies.

So I'm not sure whether the newer versions of xcms or R are responsible for the problem. Still, the problem persists with the newest versions of R and xcms :/


I've attached a mzXML file under the following link, maybe you can try to reproduce the problem? I've already tried out 2 different PCs here at work, but maybe I'm doing something completely wrong.

https://upload.uni-jena.de/data/5b2baf193db5a1.60759164/matchedFilter_test.zip

the script line that produces the problem is
xs1 <- xcmsSet(cdffiles, method = "matchedFilter", fwhm = 3, step = 0.001, steps = 2, max = 50, snthresh = 3, mzdiff = 0.001)

**Comment by stanstrup** [comment]
You have 550/0.001 = 550000 m/z slices and 7000 scans.
So you are creating a 550,000x7,000 matrix. I think that should require ~30GB. So with that step size there is no way to be more memory efficient when using matchedFilter.

**Comment by Pohnert-Lab** [comment]
So why does it work fine with older R/xcms version? In xcms 1.50.1/R v3.3.3, every process stays at around 500-600MB RAM. Something in the program architecture must have changed...

**Comment by jotsetung** [comment]
Indeed, by default `xcms` will create a very large matrix (the *profile* matrix on which `matchedFilter` runs the peak detection) - in your case (with the `step = 0.001`) that would create a too large matrix. 

The good news: in your case you can simply call `useOriginalCode(TRUE)` before running the peak detection and this matrix will not be created, but the old way of iteratively creating small profile matrices is used.

**Comment by jotsetung** [comment]
Fixed the problem. Please install the most recent `xcms` version from github: `devtools::install_github("sneumann/xcms")` and call `useOriginalCode(TRUE)` before the `xcmsSet` call.

**Comment by Pohnert-Lab** [comment]
Spoken too soon...

While it works fine with the single test file I've uploaded, it seems to again go back to the huge single matrix thing when multiple files are used for the xcmsSet call, no matter if useOriginalCode(TRUE) is used or not.

Could you please have a look at this again?

I've uploaded the multiple test files here:
https://upload.uni-jena.de/data/5b68135b47fbd8.47254689/multiple_test_files.zip

R version 3.5.0, XCMS version 3.3.3, useOriginalCode(TRUE) used.

**Comment by jotsetung** [comment]
Ups, I'll have a look at it. Thanks for reporting!

... quick question: what OS are you using and which parallel setting? An immediate explanation which comes to my mind is that parallel processing using SOCKS based parallel processing could be problematic here. SOCKS-based parallel processing creates a new R process for each thread and it could be that these processes don't *inherit* the setting set bu `useOriginalCode`. This could be tested by disabling parallel processing alltogether with `register(SerialParam())` to see if the error persists.

**Comment by jotsetung** [comment]
With `register(SerialParam())` it did work on the files, also using `register(MulticoreParam())`, but not using `register(SnowParam())`. In the latest `xcms` update I added the possibility to set the `useOriginalCode` option system-wide, also for newly spawned R processes (such as those used by the SOCK-based parallel processing).

You would have to install the latest `xcms` version from github using `devtools::install_github("sneumann/xcms")` and to add the line `options(XCMSuseOriginalCode = TRUE)` to a file named `.Rprofile` in your home directory (or the directory in which new R processes are usually started - which is in most cases the user's home directory). To check if it worked call  `useOriginalCode()` after starting R and loading the `xcms` package. This should return `TRUE`.

**Comment by Pohnert-Lab** [comment]
That fixed it, thank you very much!
