### ISSUE TITLE
xcms thinks some of the data points are centroided and some are not, prevents peak peaking from being performed

### ISSUE THREAD

**Issue by etrh** [sneumann/xcms#311]
I have come upon a very strange error that has been also covered in #202. 

```
> xdata <- findChromPeaks(raw_data, param = cwp)

Error in if (!centroided) warning("Your data appears to be not centroided! CentWave",  : 
  missing value where TRUE/FALSE needed
In addition: Warning message:
In if (!centroided) warning("Your data appears to be not centroided! CentWave",  :
  the condition has length > 1 and only the first element will be used
```

Producing a TIC, BPC, and EIC/XIC works without a problem in `xcms` on the same set of samples, but not peak picking.

Issue #202 suggests that the problem is caused by Proteowizard/msConvert, but I have already tried repeating the conversion three times and I still receive the same error.

I tried to see where the problem stems from and did this:

```
> isCentroided(raw_data) %>% table
.
FALSE  TRUE 
    2 32781 

> isCentroided(raw_data)[which(isCentroided(raw_data) == FALSE)]
F04.S0795 F08.S0797 
    FALSE     FALSE 
```

It looks like only two of the features are not centroided! Is this even possible?

I'd appreciate any feedback because I cannot locate the cause of the problem.

**Comment by jotsetung** [comment]
Can you please provide the output of your `sessionInfo()`?

Can you also call `centroided(raw_data) %>% table`?

**Comment by jotsetung** [comment]
You have a pretty old version of `xcms` (3.0.2), the current stable version (from Bioconductor 3.7) is 3.2.0. You should definitely update your Bioconductor/xcms release (e.g. using `BiocInstaller::biocLite()`). This problem should have been fixed in the newer version.

**Comment by etrh** [comment]
`xcms` 3.2.0 and `R` 3.5.1 are still not available for Scientific Linux 7.5. So I tried loading and analyzing the data on another machine (`Ubuntu 18.04.1 LTS`). I still get the same error after running `findChromPeaks` (`MSnbase_2.6.3`, `xcms_3.2.0`). The only difference right now is that when I run `centroided(raw_data) %>% table`, the result is `TRUE` (instead of `< table of extent 0 >` in my earlier reply above). However, `isCentroided(raw_data) %>% table` gives me the same result as before (2 FALSE).

**Comment by jotsetung** [comment]
Regarding `xcms` 3.2.0, AFAIK Bioconductor version 3.7 (that includes `xcms` 3.2.0) was released for R-3.5.x, so if you would run
```r
source("https://bioconductor.org/biocLite.R")
biocLite()
```
all Bioconductor packages should update to the new release.

`isCentroided` will still give you the same result, but I fixed some time ago the code in obiwarp alignment that checks whether the data is centroided. If the data is not centroided there will be a warning shown, but the call should never fail. Can you perform the alignment on the other system running `xcms` 3.2.0 or does it still fail there?

**Comment by etrh** [comment]
`Bioconductor` 3.7 requires `R` 3.5.1 which I am unable to install on my `Scientific Linux` machine.

As I mentioned in my previous post, when I run `findChromPeaks` on my `Ubuntu` machine (`xcms` 3.2.0), it fails and I receive the exact same error I have copied in my first post.

**Comment by jotsetung** [comment]
This is strange, I expected that you can install also Bioconductor 3.7 on R-3.5.0, not only on R-3.5.1.

I've added a tentative fix to the version 3.2 branch. You can install it (on your Ubuntu machine I guess) with `devtools::install_github("sneumann/xcms", ref = "RELEASE_3_7")`. Let me know if that fixes your problem - it should show a warning but should run smoothly.

**Comment by jotsetung** [comment]
All the fixes should be in the xcms of the current Bioconductor 3.8 release. So I'm closing the issue. Feel free to re-open if needed.
