### ISSUE TITLE
why is dda_spectra[[1]]@precursorIntensity always 0?

### ISSUE THREAD

**Issue by seb951** [sneumann/xcms#453]
Pardon my naive question & feel free to direct me towards a more appropriate venue: I don't get why `precursorIntensity` is always empty when running `chromPeakSpectra()` on MS2 data ? Since they come from a fragmented MS1 ion, shouldn't they have a `precursorIntensity`? Is it appropriate to say that `dda_spectra[[1]]@precursorIntensity` should equal `sum(dda_spectra[[1]]@intensity)`?

Thank you very much.

```
library(xcms)
library(msdata)
dda_file <- system.file("TripleTOF-SWATH/PestMix1_DDA.mzML",
                        package = "msdata")
dda_data <- MSnbase::readMSData(dda_file, mode = "onDisk")
cwp <- xcms::CentWaveParam(snthresh = 5, noise = 100, ppm = 10,
                     peakwidth = c(3, 30))
dda_data <- xcms::findChromPeaks(dda_data, param = cwp)
dda_spectra <- xcms::chromPeakSpectra(dda_data)
dda_spectra[[1]]@precursorIntensity
sum(dda_spectra[[1]]@intensity)
```

**Comment by jorainer** [comment]
That's actually an excellent question! The problem is (as far as I understood) that the API from Sciex does not have any function to extract this information from the raw data - thus, mzML files generated from the Sciex wiff files using proteowizard do not contain this information. I would also like to have this information for MS2 spectra, but for Sciex instruments there seems to be no option to get these - please let me know if you find a way.

If it should be identical to the integrated peak area of the chromatographic peak - I don't know. Actually, I think the precursor intensity should be the amount of ion selected for fragmentation at a single retention time (the time the MS2 spectrum is measured) - the integrated peak area is the sum of signal over the full retention time window in which the ion is measured...

**Comment by korseby** [comment]
@jorainer Hasn't this issue been resolved by #485 ? I think it can be closed.

**Comment by jorainer** [comment]
@korseby no, unfortunately that's not solved, because this is for DDA data, while #485 was for SWATH (DIA) data. Problem here is that I don't know which signal (from MS1) could be used as proper `precursorIntensity`. Open for any suggestion.

**Comment by cbroeckl** [comment]
DDA precursor selection is pretty much always based on the previous MS1 scan, so it would make sense to just use the signal intensity for the most recent MS1 scan for that precursor m/z value.   A more accurate version might be an estimated intensity based on the two MS1 scans on either side of the MS2 scan.   i.e. assume that the signal changes linearly between MS scans at 200 and 201 seconds, increasing from 1000 to 5000 counts (peak front).  an MS/MS scan at 200.25 seconds would have a precursor intensity of 2000.

**Comment by jorainer** [comment]
I've added now the `estimatePrecursorIntensity` function to calculate precursor intensities based on the suggestion from @cbroeckl (thanks!):

```r
library(xcms)
library(msdata)
fl <- proteomics(full.names = TRUE)[4]

data <- readMSData(fl, mode = "onDisk")

pi <- estimatePrecursorIntensity(data, method = "previous")
pi_int <- estimatePrecursorIntensity(data, method = "interpolation")
```

Comparing the precursor intensities extracted from the mzML files with those calculated in R:

```r
par(mfrow = c(1, 2))
plot(precursorIntensity(data), pi, xlab = "mzML", ylab = "previous")
plot(precursorIntensity(data), pi_int, xlab = "mzML", ylab = "interpolation")
```

<img width="965" alt="precursorIntensity" src="https://user-images.githubusercontent.com/5506112/85983519-ef347d80-b9e7-11ea-9f97-f3f9668be95e.png">

It is then also possible to replace/set these precursor intensities - which fixes the issue from @seb951 and makes precursor intensities also available in subsequent calls of e.g. `chromPeakSpectra`.

```r
fData(data)$precursorIntensity <- pi_int
```

This is now implemented in the current master branch on github (`xcms` version 3.11.6).

**Comment by jorainer** [comment]
Closing the issue now. Feel free to re-open if needed.
