### ISSUE TITLE
Subsetting xcmsSet with zero analyses throws an error

### ISSUE THREAD

**Issue by rickhelmus** [sneumann/xcms#463]
Hello,

Just a small issue with the _old_ XCMS interface, so perhaps not of great importance ... When an `xcmsSet` object is subset with the `[` operator and the result would be an empty object an error is thrown:

```r
xs[, character()]
 Error in array(x, c(length(x), 1L), if (!is.null(names(x))) list(names(x),  : 
  'data' must be of a vector type, was 'NULL' 

6. array(x, c(length(x), 1L), if (!is.null(names(x))) list(names(x), 
    NULL) else NULL) 
5. as.matrix.default(do.call(rbind, keep.peaks)) 
4. as.matrix(do.call(rbind, keep.peaks)) 
3. as.matrix(do.call(rbind, keep.peaks)) at methods-xcmsSet.R#2018
2. xs[, character()] 
1. xs[, character()]
```

Regards,
Rick

**Comment by sneumann** [comment]
Thx for reporting, what would be the preferred solution ? An empty xcmsSet, 
or NULL right away ? Yours, Steffen

**Comment by rickhelmus** [comment]
I would say an empty `xcmsSet`, following other (core) data types in `R`. I think this is is also what happens with subsetting the new object types from XCMS3.

**Comment by jorainer** [comment]
Should be fixed now.

**Comment by rickhelmus** [comment]
Thanks for the quick fix!

To nitpick a bit further :) Error is gone with character/numeric selection, but still present with logical selection (i.e. all elements set to `FALSE`). Furthermore, printing the empty object gives some (harmless) warnings:

```r
An "xcmsSet" object with 0 samples

Time range: Inf--Inf seconds (Inf--Inf minutes)
Mass range: Inf--Inf m/z
Peaks: 0 (about NaN per sample)
Peak Groups: 0 
Sample classes:  

Feature detection:
 o Peak picking performed on MS1.
Memory usage: 0.00514 MB
Warning messages:
1: In min(x, na.rm = na.rm) :
  no non-missing arguments to min; returning Inf
2: In max(x, na.rm = na.rm) :
  no non-missing arguments to max; returning -Inf
3: In min(x, na.rm = na.rm) :
  no non-missing arguments to min; returning Inf
4: In max(x, na.rm = na.rm) :
  no non-missing arguments to max; returning -Inf
5: In min(x, na.rm = na.rm) :
  no non-missing arguments to min; returning Inf
6: In max(x, na.rm = na.rm) :
  no non-missing arguments to max; returning -Inf
```

Cheers,
Rick

**Comment by jorainer** [comment]
Good point. I will fix also the logical subscript with all `FALSE` - and get rid of the warnings.

**Comment by jorainer** [comment]
Should work now.

**Comment by rickhelmus** [comment]
It does! Many thanks for the quick fixes!
